services:
  postgres:
    image: postgres:16-alpine
    container_name: itc_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: itc_events
      POSTGRES_USER: itc
      POSTGRES_PASSWORD: itc_secret
    volumes:
      - itc_postgres_data:/var/lib/postgresql/data

volumes:
  itc_postgres_data: