name: itc_events
description: "Book tickets for ITC campus events."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.4.0
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.4.0
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  qr_flutter: ^4.1.0
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.5
  mobile_scanner: ^7.4.0
  image_picker: ^1.2.3
  google_maps_flutter: ^2.18.0
  # Replaces default google_maps_flutter_ios so iOS can use Swift Package Manager.
  google_maps_flutter_ios_sdk9: ^2.18.13
  geolocator: ^14.0.3
  flutter_polyline_points: ^3.1.0
  url_launcher: ^6.3.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/app_logo_transparent_white.png
    - assets/app_logo_transparent_primary.png
    - assets/google_logo.png
    - assets/itc_logo.png
    - assets/khqr/khqr_logo.svg
    - assets/khqr/dollar_symbol.png
    - assets/khqr/riel_symbol.png
    - assets/payments/khqr.png
    - assets/payments/aba_pay.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Variable.ttf
    - family: NotoSansKhmer
      fonts:
        - asset: fonts/NotoSansKhmer-Variable.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/nunito_sans/NunitoSans_7pt-Regular.ttf
          weight: 400
        - asset: fonts/nunito_sans/NunitoSans_7pt-Bold.ttf
          weight: 700
